go.property("dir", vmath.vector3())

hitByLaser = hash("hit-by-laser")

function init(self)
	self.speed = 200
	self.damage = 10
	self.startPosition = go.get_position()
	self.maxLength = 350
end

function update(self, dt)
	local pos = go.get_position()
	pos = pos + self.dir * self.speed * dt
	go.set_position(pos)

	local temp = vmath.length(pos - self.startPosition)
	if temp > self.maxLength then
		go.delete()
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		--go.delete(message.other_id)
		--msg.post("/gui#ui", "add_score", {score = 100})
		msg.post(message.other_id, hitByLaser, { dmg = self.damage } )
		go.delete()
	end
end
